### ISSUE TITLE
Consider adding Copilot removal to the default change list

### ISSUE THREAD

**Issue by wjk** [Raphire/Win11Debloat#10]
This feature is so unwanted that I must disable it on every Windows 11 computer I service. However, doing this currently requires running the script in custom mode, which I would rather not do due to the possibility of irreversible borking of the system (i.e. unintended removal of that one Xbox app that cannot be restored because I mistakenly said YES).

**Comment by Raphire** [comment]
Heya,

I agree not a lot of people seem to be interested in the copilot feature, so it is a prime candidate to add to the default profile. I hope to have time later this week to do this.

I do want to set your mind at ease though about using custom mode: the script does not delete any apps (including xbox frameworks) that cannot be restored or reinstalled via the store, unless you edit the appslists manually. Only the xbox and xbox gamebar would be removed normally if you say yes to that option.

As a workaround for now I advise running the script via powershell with parameters. This way you can make the process to run easier and faster.

You can do this as follows:
1. Open powershell as an administrator.
2. Enable powershell execution for only this powershell session by entering the following command: `Set-ExecutionPolicy Unrestricted -Scope Process` 
3. In powershell, navigate to the directory where the script files were extracted. Example: `cd c:\Win11Debloat`
4. Enter this into powershell to run the script with defaults + disabling copilot: `.\Win11Debloat.ps1 -RunDefaults -DisableCopilot`

A full list of parameters is found in the README under the 'advanced method'.

**Comment by wjk** [comment]
Thanks!

**Comment by Raphire** [comment]
Copilot is now removed when running the default settings. Closing issue
