### ISSUE TITLE
`CustomAppsList` small but useful Feature: Please allow to have # comments in this file

### ISSUE THREAD

**Issue by schittli** [Raphire/Win11Debloat#103]
Hello
**Thanks a lot for sharing your great work!, your Tool makes Windows much more useful.**

**Is your feature request related to a problem? Please describe.**

* I have created a `CustomAppsList` file, 
* but for many Apps I had to google for information to decide if I want to keep or remove it
* therefore, I have added comments to the `CustomAppsList` file
* The comments helps very much to easily review this list at any time later 😀 
* If I use Win11Debloat to remove the Apps in my `CustomAppsList`, then it tries to find and remove the comment-lines, too

**Describe the solution you'd like**
It would be great if you could add a simple rule while reading the `CustomAppsList` file:
1. Each Line will be handled by Trim()
2. If the 1st Character is `#`, then the line will be remmoved

**Describe alternatives you've considered**
I could pre-process the `CustomAppsList` file before calling Win11Debloat, but then your great Quick method does no longer work 😢 

**Additional context**
I guess that other users would be happy with this small additional feature, too 😃 

Thanks a lot, kind regards,
Thomas

**Comment by Raphire** [comment]
Heya,

I'll see if I can squeeze this in soon as this seems like a useful feature :)

**Comment by Raphire** [comment]
This has been added as of dbab8e3! The `CustomAppsList` file now supports # comments just like `Appslist.txt`
