### ISSUE TITLE
Remove start menu pinned apps for default user

### ISSUE THREAD

**Issue by trackday1** [Raphire/Win11Debloat#109]
**Describe the bug**
After an in place upgrade, user accounts that have not yet logged in error during "Remove start menu pinned apps for all users". This may be expected due to not being initialized but the script then fails to continue to the "# Also apply start menu template to the default profile". If I manually copy start2.bin it works as expected.

**To Reproduce**
In place upgrade from Win10
Run script with bat or manual command
See error about existing user accounts.

**Expected behavior**
Understandably the existing accounts may not be editable until initial login but hopefully the script could continue past that error and still copy the start2.bin for the default user.

**Comment by Raphire** [comment]
Heya,

Thanks for reporting this!

The way the start menu is saved is different between Windows 10 and 11, and earlier versions of Windows 11 actually used a different format compared to now. For this reason the script checks if the expected start2.bin format already exists per user. This is indeed intended to prevent unintended consequences.

As you noted however, if any user doesn't pass this check it will skip setting the start menu for any other users and the default user. This definitely isn't intended and I'll issue a fix for this soon!

**Comment by Raphire** [comment]
This issue has been fixed as of 60f944d

Thanks for reporting!

**Comment by trackday1** [comment]
Thank you
