### ISSUE TITLE
Powershell window size is bugging out :(

### ISSUE THREAD

**Issue by MrCryptographic** [Raphire/Win11Debloat#113]
**Describe the bug**
The PowerShell window size is comically small and I can't fix it.

**To Reproduce**
Used basic Manual Installation.

**Expected behavior**
The Win11Debloat Menu to appear

**Screenshots**
![Screenshot (119)](https://github.com/user-attachments/assets/f292a8ec-4920-41f2-9702-bd9645d2c220)

**Additional context**
Nothing additional.

**Comment by Raphire** [comment]
Heya,

This is an interesting one! The script should launch with a powershell window with the default size, so maybe that somehow got changed for you?

What happens if you manually open powershell? Make sure to open it as administrator, otherwise it opens in terminal. 
![image](https://github.com/user-attachments/assets/d54e9c75-ec97-4d77-8d0e-658e6a5be7ee)

**Comment by MrCryptographic** [comment]
> Heya,
> 
> 
> 
> This is an interesting one! The script should launch with a powershell window with the default size, so maybe that somehow got changed for you?
> 
> 
> 
> What happens if you manually open powershell? Make sure to open it as administrator, otherwise it opens a window in Windows Terminal. 
> 
> ![image](https://github.com/user-attachments/assets/d54e9c75-ec97-4d77-8d0e-658e6a5be7ee)
> 
> 

I did idk if my computer just slow (because it is) or what.
Probably just loading very, very, very, slow.

**Comment by Raphire** [comment]
But does the powershell window open up eventually in normal size?

**Comment by MrCryptographic** [comment]
> But does the powershell window open up eventually in normal size?

Maybe but it takes a long time.
Probably just my computer.

**Comment by Raphire** [comment]
I see. In that case I'll close this issue as it doesn't seem related to the script itself.
