### ISSUE TITLE
Not Removing Bloat but "Getting Ready To"

### ISSUE THREAD

**Issue by weechva** [Raphire/Win11Debloat#115]
I have run the script twice. First as suggested normally, and then using the advanced method. Both times when running, per diem, it will say Getting ready to remove ___________. It continues down the list, displaying this message for each item, but upon checking the system when completed, the software components still exist.
Running Win 11 23H2.

Thank you.

**Comment by Raphire** [comment]
Heya,

I am unfortunately unable to reproduce this issue on my system and testmachines. I have pushed an update to the script that should show more information during the uninstall process if you run the script with the `-Verbose` parameter. This can be done using both the quick and advanced method explained [here](https://github.com/Raphire/Win11Debloat?tab=readme-ov-file#usage). Please note you will need to re-download the script if you want to use the advanced method.

**Comment by weechva** [comment]
Thank you, I will give it a try over the weekend and get back to you.

-Vinton Weech

**Comment by Raphire** [comment]
Heya @weechva, do you have any additional information about this issue?

**Comment by Raphire** [comment]
Closed due to inactivity
