### ISSUE TITLE
Filename with no extension 

### ISSUE THREAD

**Issue by Knight-sysdev** [Raphire/Win11Debloat#116]
![image](https://github.com/user-attachments/assets/7b70e2db-fee2-4d7e-aedc-58cec42ca6c7)
In this photo the code is trying to look for a file with no extension, it does this at every instance. you have to find and replace almost every instance of "CustomAppsList" with "CustomAppsList.txt" 
![image](https://github.com/user-attachments/assets/6f0ef1c5-66eb-4589-bd4c-106a991210f9)
It now works.

**Comment by Raphire** [comment]
The AppsList.txt is meant to be edited by end users, the CustomAppsFile however is not intended to be used that way. That's the reason I opted to leave the file without an extension.

The file is generated automatically by the script whenever you use the app selection UI to remove apps or by running the script with the `-RunAppConfigurator` parameter. Allowing the script to remember and re-apply the last used settings for app removal.

**Comment by Knight-sysdev** [comment]
> The AppsList.txt is meant to be edited by end users, the CustomAppsFile however is not intended to be used that way. That's the reason I opted to leave the file without an extension. This doesn't impact functionality, it just acts as a way to show the file is not intended to be edited.
> 
> The file is generated automatically by the script whenever you use the app selection UI to remove apps or by running the script with the `-RunAppConfigurator` parameter. Allowing the script to remember and re-apply the last used settings for app removal.

oh okay, would it not make sense to request apps list as the custom apps file list then if it's not meant to be edited?

**Comment by Raphire** [comment]
> > The AppsList.txt is meant to be edited by end users, the CustomAppsFile however is not intended to be used that way. That's the reason I opted to leave the file without an extension. This doesn't impact functionality, it just acts as a way to show the file is not intended to be edited.
> > The file is generated automatically by the script whenever you use the app selection UI to remove apps or by running the script with the `-RunAppConfigurator` parameter. Allowing the script to remember and re-apply the last used settings for app removal.
> 
> oh okay, would it not make sense to request apps list as the custom apps file list then if it's not meant to be edited?

Changing the `Appslist.txt` already changes the default selection of apps the script removes, if you edit that simply select the default option or run the script with `-RemoveApps` parameter. The `CustomAppsList` is intended as a way to remember the custom app selection you make using the script UI. So they serve different purposes.
