### ISSUE TITLE
Not Disabling/Removing CoPilot

### ISSUE THREAD

**Issue by r3db34rdh4x** [Raphire/Win11Debloat#124]
I ran your script (which overall, is very beautiful, I love the functionality you've included). However, I still have copilot in my taskbar after a restart, and it launches without issue, and I very distinctly selected the option in your script to disable it.

That's actually what brought me to your script to begin with it's hard to find documentation that works -everything is pointing to that HKCU regkey not an HKLM key or something else more permanent we can set within OS parameters like disabling a service or something.

**Comment by Raphire** [comment]
Heya,

Disabling Copilot does work on my testing machine and VM, those are both Windows 11 however. Are you running Windows 10?

**Comment by r3db34rdh4x** [comment]
No sir, I am running windows 11 current branch, home edition.

Sent from Proton Mail Android

-------- Original Message --------

**Comment by Raphire** [comment]
Hmm, that's strange then. Could you attempt to download and run [this registry file](https://github.com/Raphire/Win11Debloat/blob/master/Regfiles/Disable_Copilot.reg) manually? This is the one normally run by the script, it sets a policy to disable Copilot on both user and local machine level.

**Comment by r3db34rdh4x** [comment]
> Hmm, that's strange then. Could you attempt to download and run [this registry file](https://github.com/Raphire/Win11Debloat/blob/master/Regfiles/Disable_Copilot.reg) manually? This is the one normally run by the script, it sets a policy to disable Copilot on both user and local machine level. You may have to sign out and back in or manually restart the explorer process via taskmanager for the changes to take effect.

I've downloaded and run the regfile, rebooted my computer, and verified the registry keys persisted after the reboot. All 3 keys are where they should be, with DWORDs set to the specific decimal indicated in that registry file. But I've still got co-pilot. I wonder if it's related to the integration in edge and if we need to break edge in order to break co-pilot? But edge is a larger part of the OS if we break it we may lose other functionality unexpectedly down the road.

**Comment by Raphire** [comment]
> > Hmm, that's strange then. Could you attempt to download and run [this registry file](https://github.com/Raphire/Win11Debloat/blob/master/Regfiles/Disable_Copilot.reg) manually? This is the one normally run by the script, it sets a policy to disable Copilot on both user and local machine level. You may have to sign out and back in or manually restart the explorer process via taskmanager for the changes to take effect.
> 
> I've downloaded and run the regfile, rebooted my computer, and verified the registry keys persisted after the reboot. All 3 keys are where they should be, with DWORDs set to the specific decimal indicated in that registry file. But I've still got co-pilot. I wonder if it's related to the integration in edge and if we need to break edge in order to break co-pilot? But edge is a larger part of the OS if we break it we may lose other functionality unexpectedly down the road.

Thanks for confirming. Your comment about Edge reminded me that Microsoft has made (semi) recent changes to the Copilot app. Putting it in a seperate app and removing certain integrations. It seems it's now a seperate app in the ([Microsoft Store](ms-windows-store://pdp/?productid=9nht9rb2f4hd)). Could you confirm if it shows this app as installed on your system?

**Comment by r3db34rdh4x** [comment]
It is listed as an App under Settings > Apps > Installed Apps when searched for, yes. And I do see an uninstall button. My concern is that with every windows update it will be reinstalled. Thus I'm hoping rather than uninstall it we can break it and hide it so it can't run, but still appears to be installed? I once did this with an application by renaming its original exe to exe.old and replacing the exe with an empty .exe that did nothing but still looked like it was there.

**Comment by Raphire** [comment]
> It is listed as an App under Settings > Apps > Installed Apps when searched for, yes. And I do see an uninstall button. My concern is that with every windows update it will be reinstalled. Thus I'm hoping rather than uninstall it we can break it and hide it so it can't run, but still appears to be installed? I once did this with an application by renaming its original exe to exe.old and replacing the exe with an empty .exe that did nothing but still looked like it was there.

I understand your concern. In the past Copilot could be fully disabled/removed via the registry, but it seems with the recent change to Copilot those are now ignored. I don't know of any other way to disable it on a system level, but I will at least update the script with the option to remove the Copilot app.

**Comment by Raphire** [comment]
@r3db34rdh4x Win11Debloat now also removes the Copilot app in addition to the registry changes. Could you confirm if this new version removes Copilot as expected?

**Comment by r3db34rdh4x** [comment]
Looks like that did the trick.

**Comment by Raphire** [comment]
> Looks like that did the trick.

Thanks for confirming!
