### ISSUE TITLE
Add script to remove Mail

### ISSUE THREAD

**Issue by patrickhaley** [Raphire/Win11Debloat#13]
Remove the default Windows mail app

**Comment by Raphire** [comment]
Heya,

The mail app is intentionally not removed by default as there's quite a sizable amount of people who use it. It would be possible to make this an optional thing though, similar to the option to uninstall gaming related apps. Thoughts?

**Comment by patrickhaley** [comment]
Yea I think that's a good idea to make it optional for those going through the advanced setup.

**Comment by Newr0n** [comment]
Due to the recent changes in Microsoft Mail and the [controversy around it ](https://www.heise.de/news/Microsoft-lays-hands-on-login-data-Beware-of-the-new-Outlook-9358925.html). I would also recommend to remove it by default or at least make it optional.

**Comment by Raphire** [comment]
Thank you for your feedback.

A new option was just added to remove the old set of mail/calendar apps and/or the new Outlook for Windows mail app. e8dbbd9
