### ISSUE TITLE
How to restore missing game bar functonality?

### ISSUE THREAD

**Issue by bobalazs** [Raphire/Win11Debloat#132]
I don't understand why it would be added to default selection, as it is useful for gamers like me.

**Comment by Raphire** [comment]
Heya, 

I see you closed the issue already, but I'm curious as to what functionality you were missing?

**Comment by bobalazs** [comment]
Under the hood, AMD is essentially hooking into Windows' Game Mode (and Mixed Reality Mode) to let the OS determine when a game is active, and then use that hint to change how Windows thread scheduling works. The resulting layers of BIOS features, Xbox Game Bar software (which controls Game Mode), and AMD's drivers add up to a complete control mechanism for allocating work on the 7950X3D and 7900X3D.

Amd and its driver uses special mode to apply CPU timing and provisioning and positioning of load on cores of 7thousand series processors with large 3D cache. 
What you did however, was enable users to remove game bar by default, which is actually a sort of system process for AMD systems, as i said it allows the proper scheduling of processors. Take one look at the anandtech article. https://www.anandtech.com/show/18747/the-amd-ryzen-9-7950x3d-review-amd-s-fastest-gaming-processor

**Comment by Raphire** [comment]
Thanks for the detailed information.

Luckily Gamebar is not removed by default. It's only removed if manually selected by the user or by opting to remove gaming-related apps in custom mode. I'll see if I can add an additional warning in those cases to make users aware of the potential performance issues.
