### ISSUE TITLE
[Req] Always open Explorer to This PC

### ISSUE THREAD

**Issue by kzshantonu** [Raphire/Win11Debloat#133]
Hi,

Have been using your script and/or reg files for some time now. Very handy.

Would appreciate this new addition:

```bat
reg add "HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced" /v LaunchTo /t REG_DWORD /d 1 /f
```

Cheers

**Comment by Raphire** [comment]
Thanks for this suggestions, as of [04e313a](https://github.com/Raphire/Win11Debloat/commit/04e313aef4df9a3cdf4832bf1f5131cfac3e8a3e) Win11Debloat provides an option to change the default open location of File Explorer to `Home`, `This PC`, `Downloads` or `OneDrive`.
