### ISSUE TITLE
Did not set up a Password and cannot log in anymore 

### ISSUE THREAD

**Issue by GetSetnSetting** [Raphire/Win11Debloat#134]
**Describe the bug**
A pin was set up before without a password, upon restarting, I cannot log in to the machine using the pin

**To Reproduce**
1. Start machine after security setting updated
2. Select login and type in previously used pin 
3. Wait for login

**Expected behavior**
The pin would work as a password with the previous user

**Screenshots**

**Additional context**

**Comment by Raphire** [comment]
Heya,

I can't see how this is related to the script as it doesn't interact at all with any security settings. 

It's likely related to changes to your MS account or pc hardware. 

I have found this post here on MS forums of someone encountering this issue, with a possible solution involving a third party tool called Hiram BootCD. I don't have any experience with this tool however.
