### ISSUE TITLE
Snip & Sketch

### ISSUE THREAD

**Issue by ClemTheAlien** [Raphire/Win11Debloat#139]
I dont think the Windows Snip & Sketch feature should be removed by this debloat script. I use windows to take notes from time to time and its hard to do so without a screenshot feature. I tried flameshot for windows but it did not load or work at all when using it on a debloated windows. I believe snip & sketch should not be an application removed by this script as most users love using thr tool for notes.

**Comment by Raphire** [comment]
Heya,

I am an avid user of Snip & Sketch aswell.

Did you use the default settings for the script? The script doesn't remove Snip & Sketch by default unless you manually select it in Custom Mode. I believe the app package is called `Microsoft.ScreenSketch`.

If you haven't already it can be reinstalled here: https://apps.microsoft.com/detail/9mz95kl8mr0l?hl=en-US&gl=US

**Comment by ClemTheAlien** [comment]
I must of accidentally included screensketch in my debloat of my custom mode. Sorry for the confusion :)

**Comment by Raphire** [comment]
> I must of accidentally included screensketch in my debloat of my custom mode. Sorry for the confusion :)

No worries!
