### ISSUE TITLE
Turn off Windows Spotlight Backround

### ISSUE THREAD

**Issue by johnnyq** [Raphire/Win11Debloat#141]
**Is your feature request related to a problem? Please describe.**
Like we do with the Lock Screen We should also disable the Background from using Windows Spot Light. 

**Describe the solution you'd like**
Switch it to Picture instead

**Describe alternatives you've considered**
None

**Additional context**
![image](https://github.com/user-attachments/assets/705de634-950a-4c1a-a4ee-d6fd3e431b19)

**Comment by Raphire** [comment]
This has been added as of 8a27bc9

Thanks for the suggestion @johnnyq!
