### ISSUE TITLE
Turn Off Show Suggestions in your timeline

### ISSUE THREAD

**Issue by johnnyq** [Raphire/Win11Debloat#142]
**Is your feature request related to a problem? Please describe.**
Noticed this option was switched on for Windows 10 after running the script this should be turned off

**Describe the solution you'd like**
Turn Show suggestions in your timeline off

**Describe alternatives you've considered**
None

**Additional context**
![image](https://github.com/user-attachments/assets/92903f65-0f0d-4f06-bdfa-62a4b959fe82)

**Comment by Raphire** [comment]
This has been added as of [b7556ad](https://github.com/Raphire/Win11Debloat/commit/b7556ad0cd9b836b8396a1f457bd7f7ed787e4f7).
