### ISSUE TITLE
Run script for all users

### ISSUE THREAD

**Issue by neorai** [Raphire/Win11Debloat#149]
**Is your feature request related to a problem? Please describe.**
I have a problem when running the script with administrator permissions on a domain user. The changes are made to the administrator account, not the current user.

**Describe the solution you'd like**
I want to be able to choose which user to run the script on or run it on all user profiles

**Comment by cyberbol** [comment]
It works on 24H2 ?

**Comment by Raphire** [comment]
Heya,

This seems like a duplicate of the issue described here: https://github.com/Raphire/Win11Debloat/issues/72

**Comment by Raphire** [comment]
Closed as duplicate of #72
