### ISSUE TITLE
"WinGet Not Installed"

### ISSUE THREAD

**Issue by AlexLandherr** [Raphire/Win11Debloat#153]
I got the below error when attempting to remove some of the apps in "Custom Mode":
![image](https://github.com/user-attachments/assets/c1f5b554-dcad-493e-bd82-1f37b16195df)

What can I do about it? I really want OneDrive and Edge gone.

**Comment by Raphire** [comment]
Heya,

Winget should automatically be updated through the Microsoft Store. I would try updating it through there first. Alternatively you can find instructions on how to manually install/update it here: https://learn.microsoft.com/en-us/windows/package-manager/winget/

**Comment by AlexLandherr** [comment]
Thanks, will try it later this week.

**Comment by AlexLandherr** [comment]
> Heya,
> 
> 
> 
> Winget should automatically be updated through the Microsoft Store. I would try updating it through there first. Alternatively you can find instructions on how to manually install/update it here: https://learn.microsoft.com/en-us/windows/package-manager/winget/

I did that but got this new error in "App Removal" mode for Microsoft Edge:
![image](https://github.com/user-attachments/assets/a26e5254-a732-4ee1-bec9-36c4b03c8f65)

**Comment by Raphire** [comment]
Microsoft Edge removal is tricky, and blocked for most users outside of the EEA (European economic area). Win11Debloat does offer an option to forcefully remove edge by running the script with the `-ForceRemoveEdge` parameter.

Example:
```powershell
& ([scriptblock]::Create((irm "https://win11debloat.raphi.re/"))) -ForceRemoveEdge
```

**Comment by AlexLandherr** [comment]
It worked! Thanks for letting me know.

**Comment by Raphire** [comment]
You're very welcome!
