### ISSUE TITLE
win11:  Diagnostic data is still being sent after the command is executed

### ISSUE THREAD

**Issue by GmavionR** [Raphire/Win11Debloat#160]
win powershell run as admin

`.\Win11Debloat.ps1 -DisableTelemetry`

Diagnostic data is still being sent after the command is executed

![image](https://github.com/user-attachments/assets/105bf152-4382-46ac-926e-68caf538313b)

**Comment by Raphire** [comment]
Heya,

From google translate it seems the setting is set to 'Sending required data', this is the best setting possible with the options that Microsoft provides. The telemetry sent with this setting is described here: https://www.microsoft.com/en-us/privacy/data-collection-windows

For the scope of this script I have decided it's not worth it to use additional methods to disable all telemetry, as that is unsupported and likely to cause unintended side-effects.
