### ISSUE TITLE
Can't remove Edge

### ISSUE THREAD

**Issue by radumitrescu** [Raphire/Win11Debloat#161]
> Removing 1 apps...
Attempting to remove Microsoft.Edge...
Found Microsoft Edge [Microsoft.Edge]
Starting package uninstall...
Uninstall failed with exit code: 532

I also tried manually with `winget` but I get the same error.

**Comment by Raphire** [comment]
Heya,

The script provides an option to forcefully remove Microsoft Edge. It should offer this option if it detects the normal uninstall fails, but it seems that's only the case for a specific error code.

Luckily it's easily done manually. To do this simply run the script with the `-ForceRemoveEdge` parameter. 

Example:
```
& ([scriptblock]::Create((irm "https://win11debloat.raphi.re/"))) -ForceRemoveEdge
```

**Comment by AdreKiseque** [comment]
I think the 532 exit code is related to `setup.exe` being called by a process that hasn't been "approved". Seems to be a 24H2 thing.
