### ISSUE TITLE
New Outlook still there on new logon

### ISSUE THREAD

**Issue by Ben-5K** [Raphire/Win11Debloat#164]
**Describe the bug**
Running your script in Advanced Mode on new and full updated PC like that 
.\Win11Debloat.ps1 -RemoveW11Outlook -Silent
and after success again like that
.\Win11Debloat.ps1 -RemoveW11Outlook -Sysprep -Silent

**Expected behavior**
On a new Account there should no New Outlook 

But there is in the a New Outllook Icon still in the taskbar

Is this a bug od did i miss something?

**Comment by Raphire** [comment]
Heya, 

This seems like a duplicate of https://github.com/Raphire/Win11Debloat/issues/152

I suspect the issue is related to Windows pushing these changes after the user logs in, it certainly has done that before. I'll look into it and see if there's a way to block/mitigate this.
