### ISSUE TITLE
Change Background

### ISSUE THREAD

**Issue by julianborghuis** [Raphire/Win11Debloat#166]
Hello,

I know its not really about this script but i wanted an entry where it changes the background for the lock screen and desktop. Can you give me instructions on how to set this in the script?

**Comment by GuillaumeHullin** [comment]
Actually your proposal is not really off topic of "Debloating" Windows... I was thinking also it would be nice changing background in order to remove the "more about this image" icon on the desktop.

**Comment by Raphire** [comment]
I could see adding an option to set Background to `Picture` instead of `Windows spotlight`, like @GuillaumeHullin mentions. This is however already requested here: https://github.com/Raphire/Win11Debloat/issues/141

Any other changes would be outside of the scope of this script I feel.
