### ISSUE TITLE
Add further telemetry blocking through the hosts file as another possible option

### ISSUE THREAD

**Issue by mi-lrn** [Raphire/Win11Debloat#168]
**[Feature Request]**

Hey great script!

It would be great to have another option persay to add further telemetry blocking to windows through the hosts file.

Something similar to this:

0.0.0.0 data.microsoft.com
0.0.0.0 msftconnecttest.com
0.0.0.0 azueedge.net
0.0.0.0 activity.windows.com
0.0.0.0 bingapis.com
0.0.0.0 msedge.net
0.0.0.0 assets.msn.com
0.0.0.0 scorecardresearch.com
0.0.0.0 edge.microsoft.com
0.0.0.0 data.msn.com

(list from this video https://www.youtube.com/watch?v=IJr2DcffquI)

There is a chance this is beyond the scope of this project, in which case that's totally fine.

**Comment by GuillaumeHullin** [comment]
I don't know how @Raphire stand on that but I'm not really found of DNS blocking via host files.

**Comment by Raphire** [comment]
Heya,

WhiIe I do see the usecase for this, and I'm definitely open to adding more privacy enhanching features, but I think this kind of tweaking is indeed reaching beyond the scope of Win11Debloat.
