### ISSUE TITLE
Stoping Automatic time sync windows 11

### ISSUE THREAD

**Issue by Graham1808** [Raphire/Win11Debloat#171]
**Describe the bug**

**To Reproduce**
1. Open '...'
2. Select '....'
3. Wait for '....'

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by Graham1808** [comment]
Hi 

Since running this script Windows has stopped automatically adjusting the time on Start up

I have changes the Windows Time sync service to run automatically all my setting in date/time are set to automatic please advise 

![Screenshot (1)](https://github.com/user-attachments/assets/07282a25-d0d3-4e71-bb8d-ab6dad0e6ad9)
![Screenshot (2)](https://github.com/user-attachments/assets/ceadfcd1-96d9-4523-b269-b52748a7cc32)

**Comment by Raphire** [comment]
Heya,

Are you sure it's not actually running periodically? In my event viewer (System log, filtering by events from `Time-Service`) I can see my PC is periodically (probably at startup) syncing system time via NTP.

My W32 time service startup type is set to `Manual`, did you manually switch yours to `Automatic`?

**Comment by Graham1808** [comment]
It's not syncing the time at all I went into service.msc to change to automatic.
I've ran this script a few times happens every time and I don't know why.

**Comment by Graham1808** [comment]
Evan if I go into task schedular windows... Time and force start the tasks to shedual nothing

**Comment by Graham1808** [comment]
Apologies I will eat my hat

Could of been multiple failures 

1) dual boot system with deb 12.8
2) Adguard home blocking windows ntp so set to another source (unlikely as my work laptop never has an issue)

Ive put a pin on both and setup a regular task to fix so I don't think it's actually the script just my wonky ass setup :)

**Comment by Raphire** [comment]
Thanks for reporting back, glad you found the likely cause. I'll close the issue :)
