### ISSUE TITLE
3 more Apps for the remove list (imho)

### ISSUE THREAD

**Issue by Glitterpuke** [Raphire/Win11Debloat#18]
Hi Raphire,

today i found 3 more Apps that could fit into the "should be removed" App-List:

- devhome
- Microsoft.YourPhone
- Power Automate

Get-AppxPackage *devhome* -AllUsers  | Remove-AppxPackage
Get-AppxPackage *Microsoft.YourPhone* -AllUsers | Remove-AppxPackage
Get-AppxPackage *automate* -AllUsers | Remove-AppxPackage

I was lazy and just hit this into the powershell.

Thank your for this awesome script :-)

**Comment by Raphire** [comment]
Heya,

Thanks for the suggestions!

Were devhome and power automate installed by default for you? And did you happen to select the "Development" option during the Windows 11 setup? I believe these should only be installed if that is the case.

As for Your Phone (Phone link), that app is used by a fairly large amount of users so it is not removed by default. You can however edit the [Appslist](https://github.com/Raphire/Win11Debloat/blob/master/Appslist.txt) manually to remove it with the script.

**Comment by Glitterpuke** [comment]
Hi,

I didn't get to choose anything while installing Win 11 Pro with OOBE\BYPASSNRO and just a local Account. But i found both Apps in the Microsoft App Store when i checked for Updates and they were already installed. Maybe with Windows, maybe short after i hit the desktop and Windows updated and installed what it wanted.

Oh yeah i guess with an Android Smartphones this could be a nice App. The solutions for iOS just didn't impress me so i always delete this App. Thanks for the tip with the custom Appslist, i will look into it for my intune/autopilot deployment.

**Comment by Raphire** [comment]
Heya,

Thanks for the update, it's interesting that those apps came preinstalled then. From my work on this script, and digging into people's experiences I'm starting to believe Microsoft just rolls the dice whenever you setup a new device.

Anyway, I have added a new option to remove developer-related apps to address this. I hope this is a satisfactory solution.
