### ISSUE TITLE
Parameter cannot be found that matches parameter name 'DisableLockscrTips'

### ISSUE THREAD

**Issue by bekoeppel** [Raphire/Win11Debloat#19]
Running `.\Win11Debloat.ps1 -Silent -DisableLockscrTips` fails with:

```
A parameter cannot be found that matches parameter name 'DisableLockscrTips'
```

Running the script with `DisableLockscreenTips` works fine.

**Comment by Raphire** [comment]
Heya,

Thanks for reporting this issue. It has been fixed as of c808af0
