### ISSUE TITLE
How to turn windows spotlight back on?

### ISSUE THREAD

**Issue by Daocuong-main** [Raphire/Win11Debloat#20]
I ran your script and now I lost the windows spotlight option in the background settings. Now how do I turn it back on?

**Comment by Raphire** [comment]
Heya, 

Are you talking about the lockscreen background or the desktop background? 

The scrip should only change the lockscreen setting, but it doesn't disable/hide the spotlight option.

I have run the script on two of my machines and in both cases the option for windows spotlight remains.
![image](https://github.com/Raphire/Win11Debloat/assets/9938813/f9b6ed52-b1f9-4893-8a5a-67c74a1b3ed2)
![image](https://github.com/Raphire/Win11Debloat/assets/9938813/ab8e7dbe-b888-4381-a486-7977bc852508)

You could try to run the registry file to undo the lockscreen changes. This is found in the Win11Debloat script folder > Regfiles > Undo > Enable_Lockscreen_Tips.reg

Let me know if that works

**Comment by Daocuong-main** [comment]
You're right, the cause is kdpuvvadi's debloat-windows11, it blocks CloudContent. Thank you for taking the time.

**Comment by Raphire** [comment]
Thanks for reporting back, closing the issue :)

**Comment by rhinoreator-netizen** [comment]
t's gray and locked; I can't control it. What should I do?
