### ISSUE TITLE
Explorer randomly crashes and does not show correctly USB drives

### ISSUE THREAD

**Issue by Blistex77** [Raphire/Win11Debloat#22]
Hello,

I ran the script with these parameters : .\Win11Debloat.ps1 -RemoveApps -DisableBing -Silent -RemoveCommApps -RemoveW11Outlook -RemoveGamingApps -DisableTelemetry -HideDupliDrive -DisableWidgets -HideChat

Explorer crashed during the process, the system became irresponsive and really slow, then crashed (blue screen). At restart, everything seems fine, but the removable drives do not show properly (I've tried several) and any app such as Rufus or Balena that would look for these drives does not work (I see the process in the task manager, but the apps never pop up).

I ran the regedit to undi the -HideDupliDrive, but it doesn't seem to fix the issue.

Do you have any idea what's wrong now?

Thank you for your help!

**Comment by Raphire** [comment]
Heya,

Sorry to hear you're experiencing this issue.

The HideDupliDrive option only removes the removable drive entry in the windows explorer sidebar. Do the removable drives show up under "This PC"? I'm not sure how this would affect programs like Rufus/Balena, do other programs work fine?

**Comment by Blistex77** [comment]
I agree, it shouldn't. Could it be because explorer and the system crashed?

The removable drives show up, but after 5 to 10 minutes, it's weird and I guess this is why these apps do not work properly. I've had an issue with another executable and after applying the registry key to undo the changes + several reboot, it seems ok now.

Thanks a lot for your prompt response and thank you for your work!

**Comment by Raphire** [comment]
Glad to hear it's working now!
