### ISSUE TITLE
Restore copilot after uninstalled by script in default mode

### ISSUE THREAD

**Issue by upendra-bajpai** [Raphire/Win11Debloat#24]
Os: win 11
Script run with default app list
Affect: removed copilot
Desire restore colipt in win 11
Can anyone tell me how to do that?

**Comment by Raphire** [comment]
Heya,

The changes made by the script can be reverted by using the registry files that come with the script. 

Navigate to the script folder > Regfiles > Undo and execute the Enable_Copilot.reg file. You may need to restart your PC after applying this change.

Beware that the Copilot option is not available in all regions yet.

**Comment by upendra-bajpai** [comment]
Thanks it works.

**Comment by Raphire** [comment]
Glad to hear that, closing issue.
