### ISSUE TITLE
Disable OneDrive's "Start back up" in File Explorer on Windows 11

### ISSUE THREAD

**Issue by mriot** [Raphire/Win11Debloat#25]
This shows up on windows 11 in the file explorer path while browsing certain folders such as documents.
<img width="335" alt="zJ8Kv" src="https://github.com/Raphire/Win11Debloat/assets/24588573/c6132c96-671e-4c08-835d-adb8afc355db">

The responsible reg value is located here:
Path: `Computer\HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\StorageProvider\OneDrive`
Name: `StorageProviderKnownFolderSyncInfoSourceFactory`

And once overwritten with any value, this "feature" is immediately disabled. However, after a reboot (if one drive starts) it will enable it again.

I followed the instructions of [this answer](https://superuser.com/a/1823437) and set a deny permission for "set value" on the key and this worked like a charm. 

Would be a nice feature to add to your awesome tool!

**Comment by Raphire** [comment]
Heya,

This definitely seems like something I can look into adding. We'll have to see if this'll continue to work in the future. Microsoft can be quite stubborn in their habit of force-enabling stuff like this to continue to push their product.

**Comment by Raphire** [comment]
After looking into this a bit more I have decided not to include this feature for now. Messing with permissions of keys in the registry can cause unintended consequences that I'd rather avoid with this script.

I am definitely open to revisit this if and when a better way is found or introduced to disable this element.
