### ISSUE TITLE
remove the baked in 365 apps

### ISSUE THREAD

**Issue by BOF007** [Raphire/Win11Debloat#26]
Hello,

As others have said, thank you for this wonderful tool.

Can we add the ability to remove the baked-in office 365 / 365 one-note app + all sub-languages, as an option?

thanks!

**Comment by BOF007** [comment]
I'll have to check to give u the exact names... But it's something along
the lines of

Microsoft 365 en-ES + 3 variations
Microsoft onenote en-ES + 3 variations

Ill have mor laptops to image on the same w11 version, I'll update you on
mon/tues with exacts

Thanks for the response!

**Comment by BOF007** [comment]
Hello, Sorry about the delay, here is what I am referring too:
OS build: 22631.3007

![image](https://github.com/Raphire/Win11Debloat/assets/13402872/3243e47d-9ed4-4a0c-8be4-0baedbdf6e19)

**Comment by BOF007** [comment]
Hey, that previous post, i attached a picture to it, can you delete it from the project on your end please...

Anyways, here is the issue:
![image](https://github.com/Raphire/Win11Debloat/assets/13402872/a00f8fcc-3266-49cf-8e51-5f6dc93402f8)

**Comment by Raphire** [comment]
Heya,

Thanks for providing the addition info. This does indeed seem to be the full office suite.

Unfortunately this is a tough one, unfortunately it's not easy to uninstall this with a script. I would advise using[ the official office uninstall tool provided by Microsoft](https://support.microsoft.com/en-us/office/uninstall-office-from-a-pc-9dd49b83-264a-477a-8fcc-2fdf5dbf61d8?ui=en-us&rs=en-us&ad=us#OfficeVersion=Click-to-Run_or_MSI). Although it might be easier to re-image the machines with a standard Windows 11 image from Microsoft, so you don't have to deal with office and all the other 'software' that Dell kindly includes in their custom Windows image.
