### ISSUE TITLE
Support to disable telemetry from third party applications

### ISSUE THREAD

**Issue by joegoldman2** [Raphire/Win11Debloat#27]
[Bloatynosy](https://github.com/builtbybel/Bloatynosy) supports it and the script can be find here: https://github.com/builtbybel/Bloatynosy/blob/main/mods/remove_telemetry-third-party-apps.ps1

**Comment by Raphire** [comment]
Heya,

Thanks for the suggestion, but unfortunately I don't think that making changes to third party software falls within the scope of this script.
