### ISSUE TITLE
Support to delete some optional applications

### ISSUE THREAD

**Issue by joegoldman2** [Raphire/Win11Debloat#28]
We should have the possibility to delete optional applications like:

- Microsoft.ZuneMusic because applications, such as VLC, are widely used and can replace it (and already replaced it for many people)
- Microsoft.YourPhone
- etc

Maybe a new flag `-RemoveOptionalApps` should be introduced to let users decide if they want to delete these apps or not.

**Comment by Raphire** [comment]
Heya,

Thanks for the suggestion. The optional removal of more apps is in the works :)

**Comment by Raphire** [comment]
All applications in Appslist.txt can now be selected for removal when running the script in custom mode. f65ff49

**Comment by Raphire** [comment]
This is now possible via the UI and via command line arguments as of 323015f
