### ISSUE TITLE
"Your IT Administrator has limited access to some areas of this app" pop up when opening windows defender after running script.

### ISSUE THREAD

**Issue by whoswtr** [Raphire/Win11Debloat#30]
I went through all of the "disabled apps" in the readme and not a single word talking about removing windows defender. I'm on a personal computer and with only one user and it has admin permissions. How do I revert this??

**Comment by Raphire** [comment]
Heya,

Win11Debloat doesn't touch anything related to Windows defender. And I cannot reproduce this on my machines. 

What area of windows defender are affected/disabled?

Additionally, have you used any other scripts/programs that could affect windows defender?

**Comment by oreyg** [comment]
Interesting situation, I believe it has nothing to do with the script. I did a fresh install of Windows 11, upon installation skipped Windows Login, and unchecked all tracking boxes. With this setup it immediately showed this error without even running the script.

**Comment by oreyg** [comment]
(I'm not the creator of the original issue)
My advice would be to let Windows Update do its thing
