### ISSUE TITLE
Add Option to disable Windows CoPilot

### ISSUE THREAD

**Issue by informationinsecurity** [Raphire/Win11Debloat#32]
Your script is such a time saver! I really appreciate the work you've put into it and how easy it is to deploy en-mass. Microsoft CoPilot has made its way into some Win 11 deployments. It would be great to add an option to disable this as well. 

From my research, the following reg key modification can control it:

Disable CoPilot:
reg add HKCU\Software\Policies\Microsoft\Windows\WindowsCopilot /v TurnOffWindowsCopilot /t REG_DWORD /d 1 /f 

Enable CoPilot:
reg delete HKCU\Software\Policies\Microsoft\Windows\WindowsCopilot /f

**Comment by Raphire** [comment]
Heya,

Win11Debloat actually already has an option to disable Copilot! 

It's not part of the default settings though, you'll have to run custom mode or run the script with the -DisableCopilot parameter.

**Comment by Raphire** [comment]
Closing issue, feature already exists
