### ISSUE TITLE
Some features are possible under Windows 11 but not shown up when guided trough the options

### ISSUE THREAD

**Issue by costesbas** [Raphire/Win11Debloat#36]
Thank you very much for your script. One of the most reliable once I found. 

"Only show option for disabling context menu items for windows 10 users"

Those options are working also on Windows 11 (23H2) when we choose to revert back to the Windows 10 styled context menu.

**Comment by Raphire** [comment]
Heya,

This was somewhat intended at the time to reduce the amount of options, with the release of Windows 11 a lot more were added to the script. Additionally the context menu options often reappeared with Windows updates. 

I can definitely understand there's still a usecase for them though, I have just pushed an update so these options once again show up for W11 users that selected the revert to Windows 10 context menu option. 46df0a7
