### ISSUE TITLE
Launch script with config File (like lastsettings)

### ISSUE THREAD

**Issue by costesbas** [Raphire/Win11Debloat#37]
Is there anyway to launch the script with as command a config file containing all the parameters?

**Comment by Raphire** [comment]
Heya,

Unfortunately the script doesn't have this option. What would be your use case for this?

**Comment by costesbas** [comment]
We could preset multiple configs this way, share them.
If we use windows 10 we could launch for exemple:
`PowerShell -ExecutionPolicy Bypass -Command "& {Start-Process PowerShell -ArgumentList '-NoProfile -ExecutionPolicy Bypass -File ""%~dp0Win11Debloat.ps1 -config %~dp0Preset_Win10""' -Verb RunAs}"`

If we use windows 11 we could launch for exemple:
`PowerShell -ExecutionPolicy Bypass -Command "& {Start-Process PowerShell -ArgumentList '-NoProfile -ExecutionPolicy Bypass -File ""%~dp0Win11Debloat.ps1 -config %~dp0Preset_Win11""' -Verb RunAs}"`

I don't think the syntax of the exemples would be like this, but this is the ID.

We could generate the preset files the way it generates lastsettings.

Thank you very much for your work ;)

**Comment by ZaxLofful** [comment]
> We could preset multiple configs this way, share them. If we use windows 10 we could launch for exemple: `PowerShell -ExecutionPolicy Bypass -Command "& {Start-Process PowerShell -ArgumentList '-NoProfile -ExecutionPolicy Bypass -File ""%~dp0Win11Debloat.ps1 -config %~dp0Preset_Win10""' -Verb RunAs}"`
> 
> If we use windows 11 we could launch for exemple: `PowerShell -ExecutionPolicy Bypass -Command "& {Start-Process PowerShell -ArgumentList '-NoProfile -ExecutionPolicy Bypass -File ""%~dp0Win11Debloat.ps1 -config %~dp0Preset_Win11""' -Verb RunAs}"`
> 
> I don't think the syntax of the exemples would be like this, but this is the ID.
> 
> We could generate the preset files the way it generates lastsettings.
> 
> Thank you very much for your work ;)

All this really does it make it so you have to type less in that single command. If you already have a PowerShell file launching this, why wouldn't you just code the parameters needed there?

Or just copy the larger string and hand it around?I imagine that is already what you are doing, in which case you can just make your own config file and have it be expanded by PowerShell as parameters at run time using pipes.

https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_splatting?view=powershell-7.4

**Comment by Raphire** [comment]
> > We could preset multiple configs this way, share them. If we use windows 10 we could launch for exemple: `PowerShell -ExecutionPolicy Bypass -Command "& {Start-Process PowerShell -ArgumentList '-NoProfile -ExecutionPolicy Bypass -File ""%~dp0Win11Debloat.ps1 -config %~dp0Preset_Win10""' -Verb RunAs}"`
> > If we use windows 11 we could launch for exemple: `PowerShell -ExecutionPolicy Bypass -Command "& {Start-Process PowerShell -ArgumentList '-NoProfile -ExecutionPolicy Bypass -File ""%~dp0Win11Debloat.ps1 -config %~dp0Preset_Win11""' -Verb RunAs}"`
> > I don't think the syntax of the exemples would be like this, but this is the ID.
> > We could generate the preset files the way it generates lastsettings.
> > Thank you very much for your work ;)
> 
> All this really does it make it so you have to type less in that single command. If you already have a PowerShell file launching this, why wouldn't you just code the parameters needed there?
> 
> Or just copy the larger string and hand it around? I imagine, you are already doing that. In which case you can just make your own config file and have it be expanded by PowerShell as parameters at run time using splatting and pipes.
> 
> https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_splatting?view=powershell-7.4

This is a fair point. An additional config file would not really add much over the existing options of sharing your parameters or the other option outlined here. 

Taking into consideration that this would also bloat the script even more, I take back my previous comment. I think your use case can already be achieved quite well via existing means.

**Comment by Raphire** [comment]
Closing issue as wontfix.

**Comment by erstert3st** [comment]
Could the script not output or save the chosen options as the equal parameter after running it in "interactive" mode? 
Additionally, also modifying the Appslist.txt ?

**Comment by Raphire** [comment]
> Could the script not output or save the chosen options as the equal parameter after running it in "interactive" mode? Additionally, also modifying the Appslist.txt ?

The script actually does save the last used custom settings to the `SavedSettings` file in the root of the script. If you opted to remove a custom selection of apps these will also be saved in the `CustomAppsList` file, also in the root of the script.

If you execute the script using the `Quick method` described in the README, then these can be found at `%temp%/Win11Debloat/Win11Debloat-master`
