### ISSUE TITLE
Edge remove

### ISSUE THREAD

**Issue by zbynekdrlik** [Raphire/Win11Debloat#38]
Hi, is it possible to remove edge browser? I have run your script but edge is still here. I went through custom configuration and select it.
After success run, edge is still present.

**Comment by Raphire** [comment]
Thanks for the quick reply. 

That region should be fine yea, could you check what your current windows version is? Microsoft has been rolling out the update that allows you to uninstall Edge quite slowly. 

To do this press Windows key + R (win + R), and type winver.
It should look something like this: 
![image](https://github.com/Raphire/Win11Debloat/assets/9938813/bd6f1afc-2d39-4156-9674-ac749fca3a70)

According to Microsoft you need either [Windows 10, version 22H2 Build 19045.4123](https://support.microsoft.com/topic/february-29-2024-kb5034843-os-build-19045-4123-preview-c576e1b5-9b0d-4411-9be8-57328f41954d) or [Windows 11, version 23H2 Build 22631.3235](https://support.microsoft.com/topic/february-29-2024-kb5034848-os-builds-22621-3235-and-22631-3235-preview-5b718126-82b1-4e14-bf01-da3500a3fc88)

**Comment by Raphire** [comment]
Thanks for confirming your version.

I can reproduce the issue on my systems. I'll see if I can find an alternative way to remove it via the script. You should be able to uninstall it via the settings UI for now though.

**Comment by zbynekdrlik** [comment]
No possibility to remove edge in settings
![image](https://github.com/Raphire/Win11Debloat/assets/26905282/ec4694d6-285c-4548-b963-2de6e178e559)

**Comment by Raphire** [comment]
Oh that is weird, I can find some other users that have the same issue. There's ways to bypass this, but I personally have only been able to get it uninstalled via WinGet. If you go this route make sure to only remove Microsoft Edge, Edge WebView 2 is required for a lot of apps, even stuff like Zoom uses it from what I recall.

**Comment by Raphire** [comment]
Heya,

I have just created an experimental branch that removes edge via winget. In my limited testing so far this seems to work a treat, but I will be testing it on some more before fully releasing it. 

If you're willing to try it, please download the experimental version here: https://github.com/Raphire/Win11Debloat/tree/experimental

**Comment by zbynekdrlik** [comment]
It seems still not working
![image](https://github.com/Raphire/Win11Debloat/assets/26905282/8ea30ee1-9323-423b-9c72-159bc3cd1762)

**Comment by Raphire** [comment]
That's a shame. I do notice that your edge version is quite a few versions behind (current version is 122), could that have something to do with the fact you can't uninstall it?

**Comment by Raphire** [comment]
Uninstalling edge now works properly for EEA users, as long as uninstalling is not blocked by Windows itself.

**Comment by loadstring1** [comment]
> No possibility to remove edge in settings ![image](https://private-user-images.githubusercontent.com/26905282/312819875-ec4694d6-285c-4548-b963-2de6e178e559.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxNDYwMzMsIm5iZiI6MTcxNzE0NTczMywicGF0aCI6Ii8yNjkwNTI4Mi8zMTI4MTk4NzUtZWM0Njk0ZDYtMjg1Yy00NTQ4LWI5NjMtMmRlNmUxNzhlNTU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMxVDA4NTUzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg3NWMxZTA3ZTgyYTM0MzgwNmI4NjlmOGQ4YzIyNjU4MDZkYzFiMTI4MTY0YmM1ZTBhOTRiNDQ4MzFhZGNmZDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QtdPJxN7NGgeqqXLOLmA6bJp7_QJ7tWhN0BKUlkPesY)

Hello, I'd like to let you know i fixed this issue in my pull request. This script should be able to uninstall edge without any errors in the future. I am very happy that i can contribute to this project once again :)

**Comment by Winman486** [comment]
I am still getting error 93 is there any update to this?

**Comment by dssste** [comment]
> I am still getting error 93 is there any update to this?

If you are using loadstring1's PR, make sure you press 2 in the menu, where you get a bunch of (y/n)'s, as the stuff they added is only accessible form there (I think).

**Comment by sylv256** [comment]
@Raphire guys, seriously, come on. https://rentry.co/debloatguide#removing-microsoft-edge

**Comment by Raphire** [comment]
> @Raphire guys, seriously, come on. https://rentry.co/debloatguide#removing-microsoft-edge

Thanks for this link. I was under the impression this method didn't work anymore, but for some reason this does seem to work. I'll do some additional testing and see if I can implement this in the script.

**Comment by Raphire** [comment]
> @Raphire guys, seriously, come on. https://rentry.co/debloatguide#removing-microsoft-edge

I have released an implementation of this (with some ideas from #64 mixed in) in this branch: https://github.com/Raphire/Win11Debloat/tree/EdgeRemove-experimental

It's not fully tested but seems to work well so far. I messed up my W11 VM template, so I'll have to setup my testing environment again tomorrow to do additional testing.

**Comment by Raphire** [comment]
The option to force remove edge has been merged with the master branch as of https://github.com/Raphire/Win11Debloat/commit/6049800f10d06c8bb3d003c35716dc9af3cebb8c

**Comment by Raphire** [comment]
Closing this issue as completed. As there have been no issues reported after the feature to forcefully remove Microsoft Edge was introduced with 6049800
