### ISSUE TITLE
Ensuring that the most current version is always run..

### ISSUE THREAD

**Issue by renders** [Raphire/Win11Debloat#39]
I am enjoying using your script.. One change that I can recommend is to be able to run it remotely like the Chris Titus script. 

iwr -useb https://christitus.com/win | iex

This would ensure that the latest version is alway run. 

Thanks for all your hardwork.. 

Rob

**Comment by Raphire** [comment]
Heya,

Running a script from a URL is not something I am personally a big fan of, as it's harder to confirm what you're actually running. Having said that, if there is a demand for something like this I could implement something like this.

**Comment by Raphire** [comment]
This feature has been added in 7e89991, closing issue 😄
