### ISSUE TITLE
Outlook (New) not removed

### ISSUE THREAD

**Issue by projektilski** [Raphire/Win11Debloat#40]
Outlook (New) is not properly removed on Windows 11 23H2 Build 22621.3296
I used -RemoveW11Outlook switch
It seems the script did its job, but the pinned item in the Start Menu is still there so the user can click on it and it will install again.

**Comment by Raphire** [comment]
Heya,

Thanks for taking the time to report this. This has actually been addressed in #35. 

In short: pinned apps in the start menu can't easily be removed/edited, but Win11Debloat does have an option to completely clear the start menu of all pinned apps. You'll find this option if you select 'Custom mode' in the script menu.

**Comment by projektilski** [comment]
All other apps are removed except Outlook (New ). It is a newly created profile I was testing on and I didn't run any of those apps or check if they are installed or pinned. I can test a bit more and report. Clearing all pinned items from the Start Menu is not something I want to do, I need the selected app gone :)

**Comment by Raphire** [comment]
> All other apps are removed except Outlook (New ). It is a newly created profile I was testing on and I didn't run any of those apps or check if they are installed or pinned. I can test a bit more and report. 

That's interesting, could you open powershell and run `winget list outlook`, this should print out a list of any outlook apps installed on your PC. If you could please post the output or a screenshot of the output here. It's possible that you have a different app variant installed. 

> Clearing all pinned items from the Start Menu is not something I want to do, I need the selected app gone :)

I definitely understand it's not a good solution if you just want specific apps gone.

**Comment by projektilski** [comment]
I'll test again tomorrow and report. .Thx

**Comment by projektilski** [comment]
On the other Windows 11 installation, Outlook (New) was successfully uninstalled on a brand-new profile. So I don't know what happened on other PCs and will monitor the situation.

**Comment by Raphire** [comment]
Interesting. Was the first installation, where outlook was not correctly uninstalled, connected to the internet during setup?

**Comment by Raphire** [comment]
Thanks for reporting back. I'll close the issue for now, but feel free to open a new issue if this issue persists and/or you are able to reproduce the issue.
