### ISSUE TITLE
Interest in disabling "show more options"?

### ISSUE THREAD

**Issue by andyjphu** [Raphire/Win11Debloat#42]
I moved from win 10 to win 11 and I really disliked the new folder explorer pane compared to the the old one. 

![image](https://github.com/Raphire/Win11Debloat/assets/51890861/531ac0f3-6995-4971-92e1-651b2b2ee3c5)
The proposed change would permanently make it such that when you right click a file this pops up instead. 
![image](https://github.com/Raphire/Win11Debloat/assets/51890861/ac9d8f58-e5b0-4338-a547-a9bfce9989f6)

Would there be any interest in adding this command to the repo? Or would a fork be preferred?

reg add HKCU\Software\Classes\CLSID\{86ca1aa0-34aa-4e8b-a509-50c905bae2a2}\InprocServer32 /ve /d "" /f

The command came from: 
https://answers.microsoft.com/en-us/windows/forum/all/windows-11-right-click-explorer-menu-show-more-as/ba8dafe4-306a-403b-af0d-10a6d1ca0a9a

**Comment by Raphire** [comment]
Heya,

Thanks for your suggestion. This is actually already included in Win11Debloat, although it's not included in the default settings.  You can find this setting by selecting 'Custom mode' in the script menu, or by running the script with the `-RevertContextMenu` parameter option.
