### ISSUE TITLE
Need for target selection tools

### ISSUE THREAD

**Issue by Ricky-Tigg** [Raphire/Win11Debloat#45]
Good morning. For those who have a pre-installed Windows OS - thus hundreds of millions of devices - and have no reason to use it, but have kept it for testing purposes and then installed to the system drive(s) at least one **BSD**/**Linux** OS, this script may look attractive. I tried it under Windows 11 v. 23H2.

Opting for the option _3_ reveals many targets to select. In order to make the selection of targets efficient, the introduction of an _Select all/Deselect all_ option as well as the supports of these key compilations
- <kbd>shift</kbd> + _pad/mouse-left-click_
- <kbd>ctrl</kbd> + _pad/mouse-left-click_

as they are in _Windows Explorer_,  would be welcome.

**Comment by Raphire** [comment]
Heya,

Thanks for the suggestion.

This would definitely be of great benefit to the usability of the app selection UI. I hope to implement this soon.

**Comment by Raphire** [comment]
35fc573 has added the ability to shift + click to check/uncheck more than one app at a time., as well as a check/uncheck all option. Additionally apps are now checked/unchecked with only one click.

What would be your usecase for a only show non-installed option? It wouldn't serve a purpose functionally.
