### ISSUE TITLE
Attempt to remove Microsoft Edge reported as failed

### ISSUE THREAD

**Issue by Ricky-Tigg** [Raphire/Win11Debloat#46]
Good morning. As expected, for what Microsoft is known for, its product _Microsoft Edge_ is pre-installed, ready to be polluting. It seems a common knowledge that Microsoft made it sticky, knowing that being a highly unwanted component, like so many others, a knowledgeable user would attempt soon or later to get rid of it. However, surprisingly, the option _3_ covers it as a removal target. It didn't surprise me when this script reported a **failure** with _exit code_ subsequent to the attempt to remove said application.

What makes the notification of a failed attempt problematic is that it cannot be determined what justified it. Unlike what is notified, a search for this application - e.g. against "microsoft edge" - in the tool that is accessible via <kbd>_Windows_</kbd> indicates **no found target**. Is that an indication that after all it might have been successfully removed?

**Comment by Raphire** [comment]
Heya,

This does sound like the problem described in issue #38. Could you confirm that you got error code 93 when attempting to uninstall edge?
