### ISSUE TITLE
Pressing the `ctrl` key causes the terminal to close

### ISSUE THREAD

**Issue by Ricky-Tigg** [Raphire/Win11Debloat#47]
Hello. When attempting to remove _Microsoft Edge_ with this script, a failure message was printed in the terminal. My intention was to copy it in order to share it in this repository as part of another report originated by me. However, when a text is in focus **in the terminal** in which this script takes place, pressing <kbd>ctrl</kbd> with the intention of compiling either
- <kbd>_ctrl_</kbd> + <kbd>C</kbd> or
- <kbd>_ctrl_</kbd> + <kbd>_alt_</kbd> + <kbd>C</kbd>
 
causes the terminal to close, thus making content copying unsupported.

_P.S_. Copying in terminal is currently supported in genuine instances of PowerShell.

**Comment by Raphire** [comment]
Heya,

Thanks for reporting this, this has been fixed as of be3993e
