### ISSUE TITLE
Restore Copilot and Bing

### ISSUE THREAD

**Issue by Slo2018** [Raphire/Win11Debloat#48]
I removed Copilot and Bing and i can't restore it with REG file.

**Comment by Raphire** [comment]
What functionality are you attempting to restore? Bing websearch in the start menu?

If you live in the EEA you may need to install the package from the MS Store to restore this functionality. 

https://apps.microsoft.com/detail/9nzbf4gt040c?hl=en-US&gl=US

**Comment by Raphire** [comment]
Closed
