### ISSUE TITLE
Calendar breaks - Which app removal does it?

### ISSUE THREAD

**Issue by ITGuyattheplace** [Raphire/Win11Debloat#49]
Howdy,

Trying to figure out what breaks the calendar popup (clicking date/time in the system tray). I figured it would be Mail and Calendar but doesn't appear to be the case. Any ideas?

**Comment by Raphire** [comment]
Heya,

Does nothing pop up at all? Or is the calendar specifically not showing?

**Comment by ITGuyattheplace** [comment]
Nothing pops up at all.

Win 11 Pro 10.0.22631.3447 23H2

I'd noticed this running default settings on a few machines, I ran it again without removing communications apps but did remove Office 365 for Windows (or whatever it's called), still goes splat. I'll try and get some testing done today on other machines.

**Comment by ITGuyattheplace** [comment]
I did a fresh install, ran the debloat excluding comms apps and Office, just all the regular garbage removed. Calendar working.

Ran Get-AppxProvisionedPackage -Online $AppxApps | where-object {$_.packagename –like "*microsoft.windowscommunicationsapps*"} | remove-appxprovisionedpackage –online -Verbose

Mail is removed and calendar still working.

Looks like it's something in that first lot.

**Comment by Raphire** [comment]
That's interesting. The calendar integration with the mail & calendar apps was removed with Windows 11. To my knowledge the mail & calendar and office apps have no interaction with that menu whatsoever, and removing those definitely shouldn't break this. The script shouldn't do anything to that menu either.

Are there any other changes you make to your install?

**Comment by ITGuyattheplace** [comment]
Totally vanilla install of Win 11. All I'm doing is running the tool in the various ways described.

I'll fire up a VM and do some more testing. Probably won't happen this week.

Flippin' Micro$oft man...

**Comment by ITGuyattheplace** [comment]
Managed to get some time with this today. A non-domain joined machine running all defaults as the only admin user and the calendar is still working.

More to come

**Comment by ITGuyattheplace** [comment]
Well, my face might be a bit red on this one. It's looking like group policy is causing this, not your tool at all. Will report back with more.

**Comment by ITGuyattheplace** [comment]
Found it...

GPO: User config/Policies/Admin Templates/Start Menu and Taskbar/Remove Notifications and Action Center

**Comment by Raphire** [comment]
Thanks for reporting back on this, and no worries! Glad you managed to fix it :)

**Comment by MontejoJorge** [comment]
> Nothing pops up at all.

This is happening to me too. I have tried changing the group policy, but nothing worked. Did you manage to fix it without reinstalling @ITGuyattheplace ?

**Comment by ITGuyattheplace** [comment]
@MontejoJorge, did you have the group policy set and then you disabled/changed to diagnose?
