### ISSUE TITLE
README list of removed apps is out of sync with script

### ISSUE THREAD

**Issue by gavinbeatty** [Raphire/Win11Debloat#5]
The README list for removed apps contains `Microsoft.ZuneMusic` (the README for NOT removed apps also has `Microsoft.ZuneMusic`), but `Microsoft.ZuneMusic` is not in the list in the actual ps1 script.

I'm guessing the script is fully authoritative of what should be removed or not.

**Comment by Raphire** [comment]
Heya thanks for pointing this out. Zune music was recently moved to the list of apps that are kept and I forgot to remove it from the list in the README file. It has been removed in https://github.com/Raphire/Win11Debloat/commit/290acb1dd7588ba67f80295ad0a1365c8b41afe2
