### ISSUE TITLE
valid for Windows 11 23H2 ?

### ISSUE THREAD

**Issue by kiquenet** [Raphire/Win11Debloat#50]
Windows 11 debloat  for v11. 23H2
Quick Start Guide for step-by-step instructions on running your first optimization ?

**Comment by Raphire** [comment]
Heya,

The script has been tested with W11 23H2, and will work just fine :)

As for a quickstart guide, the script is pretty straight forward. 

All features are listed in the [README](https://github.com/Raphire/Win11Debloat/blob/master/README.md).

Instructions for how to run the script can be found [here](https://github.com/Raphire/Win11Debloat/blob/master/README.md#usage).

The script will first show a menu, where you can either choose to run the script with the default settings, or pick and choose yourself with the custom mode. This is shown below:
![image](https://github.com/Raphire/Win11Debloat/assets/9938813/30f5548f-2306-4ca7-910a-32b02e361da3)

If you choose default mode it'll show you the changes that will be made like so:
![image](https://github.com/Raphire/Win11Debloat/assets/9938813/b5bca76a-4eb3-46ec-a27c-58802b08eb4e)

And in custom mode you'll go through the options one by one like this: 
![image](https://github.com/Raphire/Win11Debloat/assets/9938813/731d06bf-d12f-4a26-a887-6ca3cebf6a6d)

After that the script will apply the changes one by one, and the script will restart the windows explorer process to apply the changes. This means the desktop will flicker for a second as things are restarted.

After that you're done.

All apps that are selected by default can easily be reinstalled via the Microsoft store. All other changes can be reverted via the registry files provided with the script, although most changes can also be reverted in the Windows settings.

**Comment by 2feath3rs** [comment]
Can it disable windows updates?

**Comment by Raphire** [comment]
@2feath3rs No, this script doesn't have an option for that. I wouldn't advise disabling updates either.

**Comment by Raphire** [comment]
Closed due to inactivity
