### ISSUE TITLE
Disable Web Search in Start Menu

### ISSUE THREAD

**Issue by vvildcard** [Raphire/Win11Debloat#53]
The following commands will disable Internet search results in the Start Menu, making it perform _much_ better and avoids data leak and telemetry issues related to sending personal searches to Bing. 

User-only option: 
Set-ItemProperty -Path "HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Search" -Name "BingSearchEnabled" -Value 0 -Type DWord

Machine-wide option: 
Set-ItemProperty -Path "HKLM:\SOFTWARE\Policies\Microsoft\Windows\Windows Search" -Name "ConnectedSearchUseWeb" -Value 0 -Type DWord

Ref: https://admx.help/?Category=Windows_10_2016&Policy=FullArmor.Policies.3B9EA2B5_A1D1_4CD5_9EDE_75B22990BC21::DoNotUseWebResults

**Comment by Raphire** [comment]
Heya, 

Win11Debloat actually already has an option to disable bing web results in the start menu search. It's a part of the default suite of settings.

**Comment by vvildcard** [comment]
Thanks for the quick response! 
I'm guessing you're referring to DisableSearchBoxSuggestions... If I'm reading it right, it is a lot more broad than the one I suggested and ultimately results in the Web Search feature being disabled, as well. I suppose you could work out a more granular approach, but the current solution is probably what most people want/expect. 

Ref: https://admx.help/?Category=Windows_10_2016&Policy=Microsoft.Policies.WindowsExplorer::DisableSearchBoxSuggestions
