### ISSUE TITLE
can't uninstall edge on 23h2

### ISSUE THREAD

**Issue by vmnvar** [Raphire/Win11Debloat#54]
checked the microsoft edge since I switched to arc browser, it says error

**Comment by Raphire** [comment]
Heya,

This is an issue that I am aware off. There's actually an open issue for it here: https://github.com/Raphire/Win11Debloat/issues/38

To summarize: Removing edge only works on systems where the region is set to a country within the EEA. And even then it might not work as there appears to be a bug in Windows that prevents some users from removing edge even with the correct region set.

I'll close this issue as a duplicate, if you have any additional info please provide it in the issue linked above.
