### ISSUE TITLE
feature request: launch debloat script with one liner

### ISSUE THREAD

**Issue by loadstring1** [Raphire/Win11Debloat#55]
Something similiar to what MAS has. Launch the script with one liner (method 1) without having to download the entire github repo.

example screenshot:
![Zrzut ekranu 2024-05-09 205906](https://github.com/Raphire/Win11Debloat/assets/156520308/c606945d-7d03-4611-aa69-9489412479f1)

**Comment by loadstring1** [comment]
Actually i just made one for you pls review my idea

pull request related to this issue:

https://github.com/Raphire/Win11Debloat/pull/56

**Comment by loadstring1** [comment]
and heres the one liner that i just made it works perfectly tested on windows 11 22h2 home edition

(must be ran with admin perms)

irm https://raw.githubusercontent.com/loadstring1/Win11Debloat/master/get.ps1 | iex

**Comment by Abyssal-Fox** [comment]
I'm not sure if this one liner could be combined with the RemoveAppsCustom list. But I assuming that it may be possible...

**Comment by Raphire** [comment]
Heya, 

This has actually been requested before in issue https://github.com/Raphire/Win11Debloat/issues/39

**Comment by loadstring1** [comment]
> Heya,
> 
> This has actually been requested before in issue #39
> 
> I'll look into this and your PR this weekend when I have more time :)

thank you my script won't support every each windows version because it uses winget to install git then clones your repo and runs "run.bat" which then starts your debloat script

its not the best but works like i wanted it to work

**Comment by Raphire** [comment]
@loadstring1 Thanks for taking the time to work on Win11Debloat. I have adapted your solution provided in #56 to include support for parameters and, among a few other changes, added a check to ensure WinGet is installed. See: 7e89991

The command to run doesn't look as clean, but it'll do the job and avoids using Invoke-Expression (iex). [This article by Microsoft](https://learn.microsoft.com/en-us/powershell/scripting/learn/deep-dives/avoid-using-invoke-expression?view=powershell-7.4) explains why iex should be avoided if possible.

Closing issue as resolved 😎

**Comment by loadstring1** [comment]
> @loadstring1 Thanks for taking the time to work on Win11Debloat. I have adapted your solution provided in #56 to include support for parameters and, among a few other changes, added a check to ensure WinGet is installed. See: [7e89991](https://github.com/Raphire/Win11Debloat/commit/7e899918a8043d85c4b755bcd9f09cc0d527d315)
> 
> The command to run doesn't look as clean, but it'll do the job and avoids using Invoke-Expression (iex). [This article by Microsoft](https://learn.microsoft.com/en-us/powershell/scripting/learn/deep-dives/avoid-using-invoke-expression?view=powershell-7.4) explains why iex should be avoided if possible.
> 
> Closing issue as resolved 😎

thank you for allowing me to contribute to this project

**Comment by ilyesm** [comment]
We are trying to dpeloy this using our RMM for onboarding automation. How do you suggest we fix cases when winget is not installed? Install Winget followed by running the line?

**Comment by Raphire** [comment]
> We are trying to dpeloy this using our RMM for onboarding automation. How do you suggest we fix cases when winget is not installed? Install Winget followed by running the line?

You could alternatively look into one of the other methods to run the script, but I think in your case simply installing WinGet may be the best option

This article has more information about WinGet that may be helpful: https://learn.microsoft.com/en-us/windows/package-manager/winget/
