### ISSUE TITLE
Recalling saved options on next run does not remove pinned apps

### ISSUE THREAD

**Issue by wired-bc** [Raphire/Win11Debloat#57]
A custom selection of removals saves a file - but when the script picks that file up on the next run the option to remove pinned apps from start menu is not applied.

**Comment by Raphire** [comment]
Heya,

Clearing the start menu relies on replacing the startmenu binary with one provided by the script. 

Could you check if in the Win11debloat script folder there's still a folder called `Start` with a `start2.bin` file inside?

**Comment by Raphire** [comment]
> Heya,
> 
> @wired-bc I am unfortunately unable to reproduce this issue myself, I do however have an idea what might be causing this.
> 
> Clearing the start menu relies on replacing the startmenu binary with one provided by the script. Could you check if in the Win11debloat script folder there's still a folder called `Start` with a `start2.bin` file inside?

@wired-bc

**Comment by Raphire** [comment]
Closing issue due to lack of information to reproduce this issue. Feel free to open a new issue in the future if the issue persists.
