### ISSUE TITLE
It is possible to know if there are new telemetry by Windows 11 Update

### ISSUE THREAD

**Issue by DruidCtba** [Raphire/Win11Debloat#58]
I wanna know if there's a way to find out if, by updating Windows 11, they didn't add more Telemetry to Windows?

Well, I was thinking, there are several programs on the web to remove and/or disable Windows 11 telemetry, and for sure Microsoft must know about it, so it occurred to me, what's stopping a Windows update KB from bringing back telemetry or even adding new ones, is that possible?

Can this script run and show this, in case they add it back or include others in a Windows update?

**Comment by Raphire** [comment]
Heya,

Microsoft has made it a habit to introduce new toggles every once in a while, those are usually related to showing ads and suggested content though. I don't know of any recent examples of new toggles related to data collection. 

If this would happen in the future it would probably be announced and tested months in advance. First rolling out to insider users for testing, and then gradually rolling out to others. 

MS is required by law to provide information about what data they collect. You can check out their summary here: https://privacy.microsoft.com/en-us/data-collection-windows

If you don't trust this then you can use tools like wireshark to check what data is sent over the network, a script like win11debloat won't be able to do this.

**Comment by Raphire** [comment]
Closing issue, feel free to open a new issue if you encounter any issues or have any other questions!
