### ISSUE TITLE
Removing "Microsoft Tips" breaks Troubleshooting

### ISSUE THREAD

**Issue by Ondrejtra** [Raphire/Win11Debloat#6]
If the option to remove bloatware is used, Microsoft Tips is also uninstalled. The application is required for Troubleshooting in system settings to work. It can be redownloaded from https://www.microsoft.com/store/productId/9WZDNCRDTBJJ, but it shouldn't be uninstalled in the first place.
Running on Windows 11.

**Comment by Raphire** [comment]
Heya, thanks for bringing this to my attention. Do you mean the [Get Help App](https://www.microsoft.com/store/productid/9PKDZBMV1H3T?ocid=pdpshare)? Microsft did indeed move a lot of the troubleshooters to this app. 

Considering I don't want to break any core windows features or settings with this script and the troubleshooters are actually useful to users I have removed Get Help from the list of apps that are removed.
