### ISSUE TITLE
Pinned apps issues

### ISSUE THREAD

**Issue by Nyox-x** [Raphire/Win11Debloat#60]
I pinned a lot apps myself in the start menu and find out it's all gone maybe because of the first y/n option after all set up.Is there a way to get my pinned apps back?

**Comment by Raphire** [comment]
Heya,

Sorry you ran into this issue. Unfortunately currently there's no backup of the overwritten startmenu layout. 

I will try to add a backup mechanism as soon as possible to prevent this issue in the future.

**Comment by Nyox-x** [comment]
OK,thanks for ur work.

**Comment by Raphire** [comment]
Thank you!

Starting with 6ec319b the start menu file will now be backed up to prevent this issue in the future.
