### ISSUE TITLE
Feature Request: DisableAIDataAnalysis (Disable Recall)

### ISSUE THREAD

**Issue by torshepherd** [Raphire/Win11Debloat#61]
Disable the new Recall feature:

https://learn.microsoft.com/en-us/windows/client-management/mdm/policy-csp-windowsai#disableaidataanalysis

Is this already supported?

**Comment by rgreening** [comment]
Oh please. The recall feature is a hackers dream and must be disabled/removed/prevented from working ever. This is a nightmare waiting to happen. No one wants their data/privacy scraped by MS this way. 

Does disabling and removing copilot perhaps already prevent this new AI recall feature or need separate handling?

Thanks for this awesome utility.

**Comment by Raphire** [comment]
Heya, 

I will look into adding this in the near future.

**Comment by Jakar510** [comment]
If not already supported, please include disabling [Windows Copilot](https://learn.microsoft.com/en-us/windows/client-management/mdm/policy-csp-windowsai#turnoffwindowscopilot) as well.

**Comment by Raphire** [comment]
> If not already supported, please include disabling [Windows Copilot](https://learn.microsoft.com/en-us/windows/client-management/mdm/policy-csp-windowsai#turnoffwindowscopilot) as well.

Luckily this is already included! 😁

**Comment by loadstring1** [comment]
me personally i avoid recall by using older windows 11 builds from official microsoft website: 21h2 and 22h2

but when they release something good in 24h2 i will most likely switch to that and find a way to disable it and make pull request like usually unless Raphire does this before me :joy:

**Comment by Raphire** [comment]
Support for disabling Recall has been added in ed029df!
