### ISSUE TITLE
How to confirm that telemetry is disabled

### ISSUE THREAD

**Issue by Raphire** [Raphire/Win11Debloat#65]
Hey guys, I'm not sure where to ask, I'm new here on github, but please, how can I know if any Windows update, the KB's of life, DID NOT BRING BACK THE TELEMETRY OR OTHER STUFF THAT THIS SCRIPT MIGHT HAVE REMOVED / DISABLED, I ask because I imagine the guys at Microsoft are not so naive as to not know about these Debloats, so my question is - is there a way for me to run a script or some program that checks for me if Microsoft didn't bring back these telemetries among other things that were disabled by this debloat?

Thanks for everyone's attention and sorry if I'm asking in the wrong place.

Cheers,

Druid®.

_Originally posted by @DruidCtba in https://github.com/Raphire/Win11Debloat/issues/31#issuecomment-2143037973_

**Comment by Raphire** [comment]
@DruidCtba, I moved the issue here, as it wasn't related to the issue you posted this in originally.

I have addressed most of your concerns already in #58, you can find a link there to what required and optional data Microsoft collects. 

To be clear: Microsoft provides settings to turn off most of their data collection and telemetry. This script uses those provided settings and turns them off for you. It's no different to you manually changing them.

There's a few settings that affect telemetry and data collection. You can check these in the Windows settings, although there may be additional settings inside specific applications. 

The most important setting is this:
![image](https://github.com/Raphire/Win11Debloat/assets/9938813/0803f712-2498-43a7-9fb5-05ab31dff1ae)

All of those methods rely on trusting Microsoft though. If you don't trust Microsoft then the only way to know for sure is manually checking your network traffic with tools like Wireshark.

**Comment by loadstring1** [comment]
> if you don't trust Microsoft then the only way to know for sure is manually checking your network traffic with tools like Wireshark.

this guy explains how to set it up on virtual machine (not wireshark but still monitors network traffic)

https://www.youtube.com/watch?v=gVi8VhLK0ro

**Comment by Raphire** [comment]
Closing issue
