### ISSUE TITLE
Explorer.exe not reopening

### ISSUE THREAD

**Issue by Gitzillas** [Raphire/Win11Debloat#67]
Hello,

New to github but I just wanted to post that when I run your script with the parameters -Silent -RemoveApps -RemoveGamingApps -DisableWidgets, Explorer .exe is terminated but then never reopens. I have to manually go in and reopen it through task manager. Are you seeing the same issue on your end?

This is on Windows 11 build 22631.3672

Thanks!

**Comment by Raphire** [comment]
Heya,

I have run into this in the past, but I wasn't able to figure it out until now. It seems like restarting explorer.exe only works properly if the powershell process and OS architecture match (ie. powershell is run as a 64 bit process on a 64 bit OS).

Do you remember if this was also the case when you ran into this issue?

**Comment by Gitzillas** [comment]
Thanks so much for getting back to me so quickly!

Yes, it is a 64bit process running on a 64bit OS. I re-ran it just to be sure and I get the explorer.exe crash with no reinitialization again.

**Comment by Raphire** [comment]
Hmm that's interesting. Do you run any antivirus other than Windows Defender?

Also, could you be so kind to try it again for me with the latest version of the script? I have added a check that prevents the issue I discussed, I just want to confirm if Windows isn't up to any funny business 🙃

**Comment by Gitzillas** [comment]
Yes, we run Crowdstrike. I could try running it before I install crowdstrike to see if that resolves it.

I pulled the latest version of the script and had the same thing happen. I'll run it before crowdstrike is installed and see if that makes a difference then get back to you. Thanks again!

**Comment by Raphire** [comment]
Thanks!

I have found a different way to restart the explorer process that may work better. Could you try running this for me in powershell: `Stop-Process -processName: Explorer`

Explorer should automatically restarted in this case, the current method the script uses relies on manually restarting powershell.

**Comment by Gitzillas** [comment]
Stop-Process -processName: Explorer asked me to confirm but then it restarted explorer without issue. Not sure if the confirm will be an issue in your script or not.

**Comment by Raphire** [comment]
That's great! [It looks like we can force our way past the confirmation](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.management/stop-process?view=powershell-7.4) 😄

I'll update the script to use this method.

P.S. I really appreciate the quick response and help with figuring out this issue!

**Comment by Gitzillas** [comment]
Just pulled the newest version and ran again, explorer restarted perfectly! Thanks so much for your help!

**Comment by Raphire** [comment]
That's great to hear! Thank you for your help aswell! 

Closing issue
