### ISSUE TITLE
‘Some settings are managed by your organization’ Message Appearing in Taskbar Settings

### ISSUE THREAD

**Issue by Othmane-ElAlami** [Raphire/Win11Debloat#68]
### Issue: "Some settings are managed by your organization" message after using the script

**Describe the bug**
After running the Win11Debloat script, the message "Some settings are managed by your organization" appears in the Taskbar settings of Windows 11.

**To Reproduce**
Steps to reproduce the behaviour:
1. Run the Win11Debloat script using the Quick method with default settings.
2. Navigate to Settings -> Personalization -> Taskbar.
3. Observe the message "Some settings are managed by your organization" at the top of the page.

**Expected behavior**
The settings should not show the "Some settings are managed by your organization" message if no policies are applied that restrict the user's ability to manage these settings.

**Screenshots**
![image](https://github.com/Raphire/Win11Debloat/assets/111425505/712401d9-e58c-4861-a66c-b115c67f21a1)

**Possible Solution**
It seems like some registry changes or policies applied by the script might be causing this message. A review of the changes made to the registry and group policies could help identify the cause.

**Comment by zoicware** [comment]
`[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Dsh]
"AllowNewsAndInterests"=dword:00000000`
just remove this key

**Comment by Othmane-ElAlami** [comment]
> `[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Dsh] "AllowNewsAndInterests"=dword:00000000` just remove this key

Thank you, the solution worked! However, I'm unsure if I should keep the issue open or if this behaviour is expected from the script.

**Comment by zoicware** [comment]
> > `[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Dsh] "AllowNewsAndInterests"=dword:00000000` just remove this key
> 
> Thank you, the solution worked! However, I'm unsure if I should keep the issue open or if this behaviour is expected from the script.

you can use this key to disable widgets without using a policy `[HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced]
"TaskbarDa"=dword:00000000`
however some things you will get that msg no matter what since theres no other way without using a policy

**Comment by Raphire** [comment]
> > > `[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Dsh] "AllowNewsAndInterests"=dword:00000000` just remove this key
> > 
> > 
> > Thank you, the solution worked! However, I'm unsure if I should keep the issue open or if this behaviour is expected from the script.
> 
> you can use this key to disable widgets without using a policy `[HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced] "TaskbarDa"=dword:00000000` however some things you will get that msg no matter what since theres no other way without using a policy

This key will disable the widgets button, but if I recall correctly it won't disable the widgets service from running in the background. That's because widgets panel can also be accessed from a shortcut (WIndows + W). 

The current implementation in the script uses the policy key to disable the widgets service entirely, but this does mean the widget setting becomes inaccessible. I'll look into alternatives later today once I have access to a W11 pc, but like @zoicware said some things can only be done using policies.

**Comment by sylv256** [comment]
https://rentry.co/debloatguide

**Comment by Raphire** [comment]
I haven't been able to find a way to disable the Widgets service without resorting to a policy. I'll keep my eye on it. If anybody does find a way to achieve this without a machine policy, please let me know.

But for now I'll close this issue.

**Comment by sylv256** [comment]
I know you think that giving people low-quality debloat scripts is helpful, but it's not. Deleting my comments only proves my point that you have no regard for the safety of peoples' systems.
https://rentry.co/debloatguide Don't use shitty debloat scripts and then come crying when your system breaks.

**Comment by greatquux** [comment]
![image](https://github.com/user-attachments/assets/becdbc5f-fc56-440a-a6b8-857e0b060d43)

**Comment by Raphire** [comment]
> I know you think that giving people low-quality debloat scripts is helpful, but it's not. Deleting my comments only proves my point that you have no regard for the safety of peoples' systems. https://rentry.co/debloatguide Don't use shitty debloat scripts and then come crying when your system breaks.

I'll bite. 

You just replied with a link and nothing else. It was not adding anything to the discussion. So i removed it. I thought it might've been accidental as you commented elsewhere with the same link.

I do find it ironic that link tells you not to run scripts while at the same time linking to scripts to get certain stuff done.

Anyhow. Nobody is forcing you to use this script. I understand why some people are against them. I've been bitten by other debloating scripts in the past, which is why I made my own and opensourced it for others to enjoy if they so please.

**Comment by zoicware** [comment]
> I know you think that giving people low-quality debloat scripts is helpful, but it's not. Deleting my comments only proves my point that you have no regard for the safety of peoples' systems. https://rentry.co/debloatguide Don't use shitty debloat scripts and then come crying when your system breaks.
🤔
<img width="873" alt="image" src="https://github.com/user-attachments/assets/d20ad3a3-ac5b-4caa-84d1-96a80f3090da">

**Comment by sylv256** [comment]
@zoicware that's like, one single security vendor out of 91. it's a notes site where people write guides.
