### ISSUE TITLE
Spotify, Linkedin were not uninstalled (default mode)

### ISSUE THREAD

**Issue by vanlil** [Raphire/Win11Debloat#69]
OS Source was: Win11_23H2_English_x64v2.iso (no updates installed), Win 11 Pro (without online account)

Spotify & LinkedIn App remained installed.

Thanks for the great tool

**Comment by Raphire** [comment]
Heya,

Could you check if they're actually installed (and found in the appslist)? It sounds like it's actually the apps the issue explained here: #41. Some apps are not actually installed, and are just stubs in the start menu. 

I haven't found a way yet to remove these individual app stubs from the start menu as they're not actually installed and the start menu file is a binary file that can't be (easily) edited.

Currently the only way for the script to remove them is to clear the start menu entirely, which is an option in the custom mode of the script.

**Comment by Raphire** [comment]
Closing issue as it's likely related to the issue discussed in #41.
