### ISSUE TITLE
Problem removing Content Delivery Manager apps

### ISSUE THREAD

**Issue by ctih** [Raphire/Win11Debloat#7]
This does not remove the placeholder apps in the start menu like TikTok, Instagram, Prime Video, WhatsApp etc.
![image](https://github.com/Raphire/Win11Debloat/assets/47664272/3d1e12ea-f4c3-43d3-89b3-ed88b15d6e9b)

**Comment by Raphire** [comment]
Heya,

I have looked into this before, unfortunately it's not easy to remove pinned apps from the start menu as it's all saved in a binary file. 

For consumer versions of windows (including Windows 11 Pro) the only reliable way to remove said apps is to completely replace the binary file. I could for example replace the start menu binary file on your system with one that has no pinned apps at all. Would that be an acceptable solution for this issue?

**Comment by Raphire** [comment]
I have just pushed an update that adds the to clear the start menu of all pinned apps. I understand this is not the most ideal solution, but as I said in my previous comment, removing specific apps is not currently possible. 

If you encounter any issues with this, or have any questions feel free to open a new issue.
