### ISSUE TITLE
add 'pause' at end of PowerShell script

### ISSUE THREAD

**Issue by WillHanighen** [Raphire/Win11Debloat#76]
it just exits so you don't know if there are any errors and it's a single line at the end of the file so its not that hard to do

**Comment by Raphire** [comment]
What method are you using to run the script? 

The Win11Debloat.ps1 script itself does wait for user input after applying the changes before exiting, unless running the script with the `-Silent` parameter.

**Comment by Raphire** [comment]
Closing issue due to lack of response.

Feel free to open a new issue if there is an area where the script doesn't wait for user input before exiting.
