### ISSUE TITLE
Suppress prompts

### ISSUE THREAD

**Issue by blademansw** [Raphire/Win11Debloat#8]
Fantastic script, but ideally it needs an option like -Silent to suppress any interactive prompts so you can run it using deployment tools (e.g. PDQ)

I just deleted the line waiting for any key to be pressed on mine ;-)

**Comment by Raphire** [comment]
Heya,

Glad to hear the script has been helpful to you! That's a great suggestion, I have just updated the script to include this functionality! 😄

Thanks!
-Raphire
