### ISSUE TITLE
Additonal Options to Disable or Turn off

### ISSUE THREAD

**Issue by johnnyq** [Raphire/Win11Debloat#83]
Option to Remove the following apps

- Get Started
- Windows Backup
- Quick assist

Option to

- Remove Microsoft Edge from the Desktop
- Unpin Microsoft Edge from the Task Bar

Settings options to turn off

- Turn off Show account related notifications occationally in Start - **Settings > Peronalization > Start**
- Set Feedback frequency to Never -  **Settings > Privacy & Security > Diagnostics & Feedback**

Options to cleanup Edge Browser to provide a more secure less privacy invasive web browsing experience.

Something that does what the article suggests below automatically would be great

https://allthings.how/how-to-debloat-and-clean-up-microsoft-edge/

**Comment by Raphire** [comment]
Heya,

Thanks for these suggestions. I'll look into these later today.

I do know that Get Started unfortunately cannot be uninstalled anymore on Windows 11. The same goes for Windows Backup. Microsoft includes these apps as part of a Windows Feature Pack and removing that breaks a lot of unrelated OS functionality.

**Comment by Raphire** [comment]
@johnnyq As said in my previous comment it's not possible to uninstall Get Started and Windows Backup in Windows 11.

I have however added these options to the script:
* Quick assist can now be removed
* Turning off suggested content now also disables Account related notification in Start
* Turning off telemetry now also sets feedback frequency to never

As for removing the edge shortcuts: I don't know of any way to remove taskbar shortcuts via powershell. But a new option will soon be added that allows you to force uninstall Microsoft Edge, this should also remove any taskbar/desktop links.

As for the other edge tweaks you mentioned, I'd really like to see what's possible with that and implement it into the script. Could you make a seperate issue for this?

**Comment by johnnyq** [comment]
Wow Fantastic @Raphire You are way to quick we really appreciate it.

Ill go ahead and submit a new feature request for edge. That in itself would be huge. Deff save someone from manually going to through that painsaken process of flipping switches for each computer and user. hhaha

**Comment by Raphire** [comment]
> Wow Fantastic @Raphire You are way to quick we really appreciate it.
> 
> Ill go ahead and submit a new feature request for edge. That in itself would be huge. Deff save someone from manually going to through that painsaken process of flipping switches for each computer and user. hhaha

Thank you! 

I do occasionally use Edge myself, so I definitely feel the pain with going through all the settings to get it into a useable state.

Closing this issue 🙃
