### ISSUE TITLE
Feature: Turn off - Show me notifications in the Settings app

### ISSUE THREAD

**Issue by johnnyq** [Raphire/Win11Debloat#86]
Here's another one that should be switched off as well.

Settings > Privacy & security | Turn off Show me notifications in the Settings app

**Comment by johnnyq** [comment]
Im not sure if this one should be on of off

![image](https://github.com/Raphire/Win11Debloat/assets/1812594/e3fca7a3-8c60-4e28-9c79-70dc6c75106c)

**Comment by Raphire** [comment]
Heya!

Both of these features have been added as of [c8e65b4](https://github.com/Raphire/Win11Debloat/commit/c8e65b460f6f603df625d3a73bb63b40be8ecc82)

Activity history will be turned off together with other telemetry and data collection.

The settings notifications will be disabled together with all other suggested content, notifications and ads.
