### ISSUE TITLE
Feature: Remove Gallery from the File Manager

### ISSUE THREAD

**Issue by johnnyq** [Raphire/Win11Debloat#87]
Deff can be remove

![image](https://github.com/Raphire/Win11Debloat/assets/1812594/579bff5a-afa7-4742-8b97-8b1795267782)

```
Windows Registry Editor Version 5.00

[-HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Desktop\NameSpace\{e88865ea-0e1c-4e20-9aa6-edcd0212c87c}]

```

Reference
https://www.elevenforum.com/t/add-or-remove-gallery-in-file-explorer-navigation-pane-in-windows-11.14178/#Two

**Comment by Raphire** [comment]
Heya,

Thanks for the suggestion! An option to disable this has been added as of [c8e65b4](https://github.com/Raphire/Win11Debloat/commit/c8e65b460f6f603df625d3a73bb63b40be8ecc82)
