### ISSUE TITLE
Windows search no longer working after script

### ISSUE THREAD

**Issue by msdarck** [Raphire/Win11Debloat#90]
It just shows a blank screeen
![image](https://github.com/Raphire/Win11Debloat/assets/47271052/fe7a2aab-3c93-4164-8f05-7fccbb3af430)

If I click out of the search box (in the blank space), it goes back to normal
![image](https://github.com/Raphire/Win11Debloat/assets/47271052/4cb386fe-0261-4d14-9082-77b78133b094)

But if I focus the search box again, it shows the blank screen back

**Comment by Raphire** [comment]
@msdarck Thanks for reporting back! Glad you managed to fix it :)
