### ISSUE TITLE
No video signal after running script as admin

### ISSUE THREAD

**Issue by keylimecharm** [Raphire/Win11Debloat#91]
After running the script as admin and rebooting, the PC gives no video signal.

**To Reproduce**
1. In the last automatic update of Win11, run the script as admin. 
2. Select option '0' and un-check Clipchamp (as to not unsinstall it).
3. Wait for the script to finish running. 
4. Turn the PC completely off. 
5. Turn PC on again. 

After this the PC, can be turn on and the fans spin, but it gives no video signal. 
Also, holding the power button to turn it off doesn't work, so I had to power off the PC fliping the switch in the power suppy. 

**Things I've tried:**
-Booting the PC with no storage attached. 
-Clearing the CMOS. 
-Reseating/reconnecting GPU and RAM.
-Tested the PC with another GPU installed (same issue, but both the 950 and the extra GPU work on my backup PC). 

**PC Parts:**
Ryzen 5 5500
GTX 950 (known working, tested on another pc) 
A520M S2H
2x 16gb Kingston Fury Beast 3200MHz
WD SN570 NVMe 500gb

I ordered a replacement motherboard to do further testing.

**Comment by Raphire** [comment]
Heya, 

Sorry you're running into this issue. 

I have a hard time wrapping my head around this issue and how this could be related to this script. From your description it seems your PC isn't [POSTing](https://en.wikipedia.org/wiki/Power-on_self-test) at all. This does indicate a hardware issue.

**Comment by Raphire** [comment]
@keylimecharm Do you have any updates on your issue?

**Comment by Raphire** [comment]
Closing issue due to lack of response and the fact the issue seems to be hardware related.
