### ISSUE TITLE
Restore windows

### ISSUE THREAD

**Issue by mauamolat** [Raphire/Win11Debloat#95]
How do we restore windows apps or customizations done with the script?

**Comment by Raphire** [comment]
Heya!

All apps (with a few exceptions) can be found & reinstalled through the Microsoft Store.

Most of the tweaks can be reverted by running the individual registry files that are provided with the script. You can view/download them here: https://github.com/Raphire/Win11Debloat/tree/master/Regfiles/Undo

You may need to restart your PC (or Windows Explorer) for the registry changes to apply though.

The start menu pinned apps can be brought back, but this requires you to manually replace the file with the backup that the script creates. I outlined how to revert the start menu [here](https://github.com/Raphire/Win11Debloat/issues/94#issuecomment-2222968243).
